version: '2'
services:
    memcached:
      image: memcached
      restart: unless-stopped
    db:
      image: mysql
      restart: unless-stopped
      volumes:
        - /dev/log:/dev/log
        - ./data/application/mysql/runtime:/var/lib/mysql
        - ./data/application/mysql/dump:/dump
      env_file:
        - ./data/config/env
      environment:
        MYSQL_DATABASE: vimbadmin
        MYSQL_USER: vimbadmin
      logging:
        driver: journald
    spamassassin:
        image: indiehosters/spamassassin
        links:
          - dovecot
        restart: unless-stopped
        volumes:
          - /dev/log:/dev/log
        logging:
          driver: journald
    postfix:
      image: indiehosters/postfix
      hostname: "$HOST"
      links:
        - db
        - spamassassin
        - dovecot
      restart: unless-stopped
      volumes: 
        - ./data/config/opendkim:/etc/opendkim
        - ./data/config/TLS:/ssl 
        - /dev/log:/dev/log
      ports:
        - "25:25"
        - "587:587"
      logging:
        driver: journald
      env_file:
        - ./data/config/env
    dovecot:
      image: indiehosters/dovecot
      links:
        - db
      restart: unless-stopped
      volumes:
        - ./data/application/dovecot/mail:/mail
        - ./data/config/TLS:/ssl
        - /dev/log:/dev/log
      ports:
        - "993:993"
        - "995:995"
      env_file:
        - ./data/config/env
      logging:
        driver: journald
    vimbadmin:
      image: gorlug/vimbadmin
      hostname: "$HOST"
      links:
        - db
        - memcached
        - postfix
      volumes_from:
        - dovecot 
      restart: unless-stopped
      volumes:
        - ./data/config/salts:/salts
        - ./data/config/indie.signed.mobileconfig:/var/www/html/public/indie.signed.mobileconfig
      env_file:
        - ./data/config/env
      environment:
        APPLICATION_ENV: production
        CLOUD_HOST: "$HOST"
      logging:
        driver: journald
    nextcloud:
      image: gorlug/nextcloud-email
      links:
        - db
        - dovecot
      restart: unless-stopped
      volumes:
        - ./data/application/nextcloud/apps:/var/www/html/apps
        - ./data/application/nextcloud/config:/var/www/html/config
        - ./data/application/nextcloud/data:/var/www/html/data
      env_file:
        - ./data/config/env
      logging:
        driver: journald
    nextcloud-web:
      image: nginx
      volumes:
        - ./nextcloud-nginx.conf:/etc/nginx/nginx.conf:ro
      links:
        - nextcloud
      restart: unless-stopped
      volumes_from:
        - nextcloud
      environment:
        - VIRTUAL_HOST
      logging:
        driver: journald
    roundcube:
      image: gorlug/roundcube-email
      restart: unless-stopped
      volumes:
        - ./data/application/roundcube:/data
      links:
        - dovecot
        - postfix
      env_file:
        - ./data/config/env
      logging:
        driver: journald
    web:
      image: nginx
      hostname: "$HOST"
      links:
        - vimbadmin
        - nextcloud-web
        - roundcube
      restart: unless-stopped
      volumes_from:
        - vimbadmin
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./data/config/TLS:/ssl
      environment:
        - HOST
        - AUTOCONFIG_HOST="$HOST"
      ports:
        - "$PORT:443"
      logging:
        driver: journald
