#!/bin/bash

. ./data/config/env

cp indie.mobileconfig data/config/indie.mobileconfig
sed -i "s/PRIMARY_HOSTNAME/${HOSTNAME}/g"  data/config/indie.mobileconfig
sed -i "s/CLOUD_HOSTNAME/${CLOUD_HOSTNAME}/g"  data/config/indie.mobileconfig
sed -i "s/UUID1/$(cat /proc/sys/kernel/random/uuid)/g"  data/config/indie.mobileconfig
sed -i "s/UUID2/$(cat /proc/sys/kernel/random/uuid)/g"  data/config/indie.mobileconfig
sed -i "s/UUID3/$(cat /proc/sys/kernel/random/uuid)/g"  data/config/indie.mobileconfig
sed -i "s/UUID4/$(cat /proc/sys/kernel/random/uuid)/g"  data/config/indie.mobileconfig

cat data/config/TLS/cert.pem data/config/TLS/chain.pem > data/config/TLS/ssl_certificate.pem

openssl smime  -sign  -signer data/config/TLS/cert.pem -inkey data/config/TLS/ssl_private_key.pem -certfile data/config/TLS/ssl_certificate.pem  -nodetach -outform der -in data/config/indie.mobileconfig -out data/config/indie.signed.mobileconfig
