#!/bin/bash -eux
docker run \
    --rm \
    --user 0 \
    -e PASSPHRASE=$2 \
    -v $PWD/duplicity/.cache:/home/duplicity/.cache/duplicity \
    -v $PWD/duplicity/.gnupg:/home/duplicity/.gnupg \
    -v $PWD/data:/data \
    -v $1:/source:ro \
    wernight/duplicity \
    duplicity \
        --verbosity info \
        --time $3 \
        file:///source \
        /data
